field: f3797235-3342-4713-ab42-6c67225eddf4 # Artikelinhoud
fieldLayouts:
  3fc01b77-7d72-45ee-8bee-28ce67a3c3f9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3cb5b4a9-311b-4d92-83bf-6dc2c3f07d71 # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dffd2093-d3da-4227-80f9-7fead4884b39
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2eaf4161-17ae-4704-9785-a4a543f63888
        userCondition: null
fields:
  3cb5b4a9-311b-4d92-83bf-6dc2c3f07d71: # Tekst
    columnSuffix: mojrgovm
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Tekst
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      ckeConfig: 91c13cae-c1e9-4dcf-b461-385b050a7e63 # Simple
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: footer
name: Footer
sortOrder: 2
