fieldLayouts:
  aa378fbf-03d2-4f92-a413-5fb418f35c73:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 63ecaeef-c18d-4a09-ae26-09294163e643
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6436c085-6043-418a-b5cd-38931dbaef58
        userCondition: null
handle: contact
hasTitleField: false
name: Contactformulier
section: ad5d57df-6a87-460c-8aa5-ee4164b67f5a # Contactformulier
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
