fieldLayouts:
  9e2902e0-8519-409e-828d-3000f9575778:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Titel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8dcdbbe9-f32f-4056-b04b-f4e58613f534
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 015e99c0-7464-4e6a-bf45-bf6e9ae205be # Inhoud
            instructions: null
            label: Inhoud
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0496401c-c8a3-4cff-8092-afb4e79d73d0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8ef7f2ee-3ba2-4dc0-ba05-c31ffa52d4bf
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 6dd71438-05db-4abe-a944-f4585b81c793 # Info
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
