fieldLayouts:
  1fbca6da-b56b-407a-8149-4a0ce2be471d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 40d42585-46c6-4d3e-9f79-2a56af02832c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c35f9b6a-99a6-45fa-9ae9-285e44c950d3 # Student
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 741acc8a-f48f-4cb6-b05b-86e745a46b8a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c4761e9b-b01c-44b9-883a-dd09fe65860d # Cursus
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c782cc8e-1e10-496e-8e9c-e36711239361
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9d9b9fb7-5b02-4a3d-aa20-d7136177a696
        userCondition: null
handle: inscription
hasTitleField: false
name: Inschrijving
section: 255e9385-140e-4aab-b7b5-f498f6b1ef0d # Inschrijvingen
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{student.one().id}-{course.one().id}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
