fieldLayouts:
  e9c263dd-6038-446f-8c8f-06975efc383b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e5568a4a-4c59-4a0c-a142-84958e9b2423
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8c935bb3-953b-4ab7-9a17-699a5433e36a
        userCondition: null
handle: newsHomepage
hasTitleField: false
name: 'Nieuws overzichtspagina'
section: fe056d46-d7d1-49fe-a2a4-60f6a2ccf2fd # Nieuws overzichtspagina
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
