fieldLayouts:
  b427c970-5b13-401f-aa18-5669e4fab4ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Naam
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 17405c4b-9bb7-4cfd-b7e1-482828e6b8ea
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: true
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 05afb208-31a7-44d0-b5b7-00c447329b8d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 52865d00-1264-44be-80b1-9bf8835dcff0
        userCondition: null
fs: bannerUploads
handle: bannerImages
name: Bannerafbeeldingen
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
