fieldLayouts:
  da4ab635-1a2d-49a3-9927-c4ab0a5a94dc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ef278c1d-57ef-432a-86fa-5f1ab0d77692
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Alt-tekst (korte beschrijving)'
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: true
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 38a23148-755d-4fd3-a3fd-fb1113186cdf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b5dcb4df-5b9e-40fa-b347-4f255fd9de2c
        userCondition: null
fs: campusUploads
handle: campusImages
name: Campusafbeeldingen
sortOrder: 6
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
