fieldLayouts:
  7a084921-8401-4d65-af67-5d5e49804077:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Naam
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4e870e67-def7-4373-bfe2-b592d0c36a0a
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Alt-tekst (korte beschrijving)'
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: true
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 29a32d0b-e6d8-47b3-84d8-df8d3f72702a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4708af5b-3b07-435e-bef4-d5bcb6e979c1
        userCondition: null
fs: uploadsVoorNieuws
handle: newsImages
name: Nieuwsafbeeldingen
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
