columnSuffix: null
contentColumnType: string
fieldGroup: 1349ef6d-2683-4de4-8756-f2eebe8fbc19 # Cursussen
handle: courseImage
instructions: null
name: Cursusafbeelding
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:1a091ca9-8a55-4f30-a303-93b4d51b46c3' # Cursusafbeeldingen
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:359aa862-f1c1-460b-9daf-fc91c3bb49cc' # Afdelingsiconen
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:1a091ca9-8a55-4f30-a303-93b4d51b46c3' # Cursusafbeeldingen
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
