columnSuffix: jeheyggy
contentColumnType: text
fieldGroup: dd42cf6b-e419-4f02-8749-501bd50e3efd # Common
handle: credits
instructions: null
name: Credits
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: e9ae2235-825e-4151-8713-50deaa0cadf5 # Extended
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
