columnSuffix: jmksopcz
contentColumnType: datetime
fieldGroup: 1349ef6d-2683-4de4-8756-f2eebe8fbc19 # Cursussen
handle: startDate
instructions: null
name: Startdatum
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
