currLabel: 'Plugin Store'
customIcon: null
enabled: true
handle: plugin-store
icon: plugin
layout: d301ea2b-5acc-4192-b929-03844bc8cb9c # Default
level: 1
newWindow: false
parent: null
prevLabel: 'Plugin Store'
prevLevel: 1
prevParent: null
prevUrl: plugin-store
sortOrder: 8
subnavBehaviour: null
type: craft
url: plugin-store
