currLabel: Assets
customIcon: null
enabled: true
handle: assets
icon: asset
layout: d301ea2b-5acc-4192-b929-03844bc8cb9c # Default
level: 1
newWindow: false
parent: null
prevLabel: Assets
prevLevel: 1
prevParent: null
prevUrl: assets
sortOrder: 4
subnavBehaviour: null
type: craft
url: assets
