currLabel: Categories
customIcon: null
enabled: true
handle: categories
icon: tree
layout: d301ea2b-5acc-4192-b929-03844bc8cb9c # Default
level: 1
newWindow: false
parent: null
prevLabel: Categories
prevLevel: 1
prevParent: null
prevUrl: categories
sortOrder: 3
subnavBehaviour: null
type: craft
url: categories
