currLabel: Entries
customIcon: null
enabled: true
handle: entries
icon: section
layout: d301ea2b-5acc-4192-b929-03844bc8cb9c # Default
level: 1
newWindow: false
parent: null
prevLabel: Entries
prevLevel: 1
prevParent: null
prevUrl: entries
sortOrder: 2
subnavBehaviour: null
type: craft
url: entries
