currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: settings
layout: d301ea2b-5acc-4192-b929-03844bc8cb9c # Default
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 7
subnavBehaviour: null
type: craft
url: settings
