defaultPlacement: end
enableVersioning: true
handle: bannerTexts
name: Bannerteksten
propagationMethod: all
siteSettings:
  9af05224-5be5-4ac1-8f64-727b7fbee4d3: # MySchool
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
