defaultPlacement: end
enableVersioning: true
handle: contact
name: Contactformulier
propagationMethod: all
siteSettings:
  9af05224-5be5-4ac1-8f64-727b7fbee4d3: # MySchool
    enabledByDefault: true
    hasUrls: true
    template: contact/index.twig
    uriFormat: contact
type: single
