defaultPlacement: end
enableVersioning: true
handle: newsHomepage
name: 'Nieuws overzichtspagina'
propagationMethod: all
siteSettings:
  9af05224-5be5-4ac1-8f64-727b7fbee4d3: # MySchool
    enabledByDefault: true
    hasUrls: true
    template: news/index.twig
    uriFormat: nieuws
type: single
